{
    "name": "HR Project Management",
    "summary": "SLA-driven project and recurring task foundation for HR consulting operations.",
    "description": """
        Foundation module for StellarHR custom project management workflow.
        Phase 1-4 includes SLA setup, HR functions, task templates, recurring task spawn,
        task dependencies, feedback, progress tracking, session-based check-in gate,
        document folder hierarchy, and geo-location capture.
    """,
    "author": "Mobipine Limited",
    "website": "https://mobipine.com",
    "category": "Services/Project",
    "version": "19.0.1.0.0",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "web",
        "project",
        "hr",
        "hr_attendance",
        #"industry_fsm",
        "enhanced_document_management",
    ],
    "data": [
        "security/stellar_hr_groups.xml",
        "security/ir.model.access.csv",
        "security/stellar_hr_rules.xml",
        "data/ir_sequence_data.xml",
        "data/stellar_hr_cron_data.xml",
        "views/project_sla_views.xml",
        "views/project_hr_function_views.xml",
        "views/project_task_template_views.xml",
        "views/res_partner_views.xml",
        "views/project_project_views.xml",
        "views/project_task_views.xml",
        "views/project_task_documents_views.xml",
        "views/project_checkin_session_views.xml",
        "views/res_partner_views.xml",
        "views/menu_views.xml",
        "views/stellar_document_type_views.xml",
        "wizards/attendance_checkin_wizard_views.xml",
    ],
    "external_dependencies": {},
    "assets": {
        "web.assets_backend": [
            "mobipine_odoo_project_management/static/src/js/geolocation.js",
            "mobipine_odoo_project_management/static/src/xml/geolocation.xml",
            "mobipine_odoo_project_management/static/src/js/attendance_menu_patch.js",
            "mobipine_odoo_project_management/static/src/js/session_gate.js",
            "mobipine_odoo_project_management/static/src/js/session_gate_error_handler.js",
            "mobipine_odoo_project_management/static/css/session_gate.css",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
    "post_init_hook": "mobipine_odoo_project_management.hooks.post_init_hook",
    "post_migrate": "mobipine_odoo_project_management.hooks.post_migrate_hook",
}