from . import project_sla
from . import project_hr_function
from . import project_task_template
from . import project_spawn_log
from . import project_checkin_session
from . import res_partner
from . import project_project
from . import project_task
from . import ir_attachment
from . import stellar_task_feedback
from . import stellar_task_progress
from . import stellar_attachment_req
from . import stellar_document_type
from . import hr_employee
from . import hr_attendance
from . import ir_ui_menu
